### ISSUE TITLE
F4: Implement Navigation Controls

### ISSUE THREAD

**Issue by ResidentAlien** [Techie09/StumpLug#4]
Implement a base skeleton for navigating pages.

**Comment by ResidentAlien** [comment]
Base skeleton implemented.

**Comment by KayK737** [comment]
Failed Code Review: https://github.com/Techie09/StumpLug/pull/5

**Comment by Techie09** [comment]
Merged To Main Pull Review #8

**Comment by Techie09** [comment]
Checked into F4 Branch and Merged to Master
